# Generated by Django 5.0.6 on 2024-07-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('Marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Timing', models.PositiveIntegerField()),
                ('num_Questions', models.PositiveIntegerField()),
                ('Total_Marks', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=100)),
                ('is_Correct', models.BooleanField(default=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Test.question')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.answer')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.question')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('Total_Marks', models.IntegerField()),
                ('Total_Attempted', models.IntegerField()),
                ('Accuracy', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Test.test'),
        ),
    ]
