# Generated by Django 5.0.6 on 2024-07-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_question_img_solution_question_text_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_Solution',
            field=models.CharField(blank=True, null=True),
        ),
    ]
