# Generated by Django 5.0.6 on 2024-07-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_alter_question_img_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_Solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
