# Generated by Django 5.0.6 on 2024-07-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_alter_question_text_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_Solution',
            field=models.ImageField(blank=True, null=True, upload_to='Assests/Solutions/'),
        ),
    ]
