# Generated by Django 5.0.6 on 2024-07-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_catagory_test_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Catagory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.catagory'),
        ),
    ]
